# fly config for the worker app
app = "lineoa4stt-worker"
primary_region = "sin"

[build]

# No HTTP service needed for the worker

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  PROCESS = "worker"
